name = "ShapeConstrainedStats"
uuid = "f73efea4-6d21-11e9-25ff-9b1447cfbccb"
authors = ["Nikos Ignatiadis <nikos.ignatiadis01@gmail.com>"]
version = "0.1.0"

[deps]
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
